FROM golang:1.25.4-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . ./

RUN go build -o worker ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/worker .

EXPOSE 8080

CMD ["./worker"]